name: pprab
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.9.0
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.5.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  intl: ^0.18.1
  provider: ^6.0.5
  responsive_ui: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/
