List<String> places = [
  'Gaborone',
  'Mahalapye',
  'Francistown',
  'Jwaneng',
  'Sowa Town',
  'Selibe Phikwe',
  'Mogobane',
  'Otse',
  'Ramotswa',
  'Ramotswa Station/Taung ',
  'Tlokweng',
  'Betesankwe',
  'Palla Road',
  'Diabo',
  'Dipotsana',
  'Gasita',
  'Kanye',
  'Kgomokasitwa',
  'Lefoko',
  'Lekgolobotlo',
  'Lorolwana',
  'Lotlhakane',
  'Lotlhakane West',
  'Magotlhwane',
  'Manyana',
  'Maokane',
  'Mogonye',
  'Mokhomba',
  'Molapowabojang',
  'Moshaneng',
  'Moshupa',
  'Ntlhantlhe',
  'Pitseng',
  'Ralekgetho',
  'Ranaka',
  'Segwagwa',
  'Seherelela',
  'Selokolela',
  'Semane',
  'Sese',
  'Sesung',
  'Tlhankane',
  'Tshwaane',
  'Tsonyane',
  'Bethel',
  'Borobadilepe',
  'Digawana',
  'Dikhukhung',
  'Dinatshana',
  'Ditlharapa',
  'Gamajalela',
  'Gathwane',
  'Good Hope',
  'Hebron',
  'Kangwe',
  'Kgoro',
  'Lejwana',
  'Leporung',
  'Logagane',
  'Lorwana',
  'Mabule',
  'Madingwana',
  'Magoriapitse',
  'Makokwe',
  'Malokaganyane',
  'Marojane',
  'Metlobo',
  'Metlojane',
  'Mmakgori',
  'Mmathethe',
  'Mogojogojo',
  'Mogwalale',
  'Mokatako',
  'Mokgomane',
  'Molete',
  'Motsentshe',
  'Musi',
  'Ngwatsau',
  'Papatlo',
  'Phihitshwane',
  'Pitsana-Potokwe',
  'Pitsane Siding',
  'Pitshane molopo',
  'Rakhuna',
  'Ramatlabama',
  'Sedibeng',
  'Sekhutlane',
  'Sheep Farm',
  'Tlhareseleele',
  'Tshidilamolomo',
  'Tswaaneng',
  'Tswagare/ Lothoje/ Lokalana',
  'Tswanyaneng',
  'Ngwaketse West',
  'Itholoke',
  'Kanaku',
  'Keng',
  'Khakhea',
  'Khonkhwa',
  'Kokong',
  'Kutuku',
  'Mabutsane',
  'Mahotshwane',
  'Morwamosu',
  'Sekoma',
  'Boatlaname',
  'Dikgatlhong',
  'Ditshukudu',
  'Gabane',
  'Gakgatla',
  'Gakuto',
  'Gamodubu',
  'Hatsalatladi',
  'Kgope',
  'Kopong',
  'Kubung',
  'Kumakwane',
  'Kweneng',
  'Lentsweletau',
  'Leologane',
  'Lephephe',
  'Losilakgokong',
  'Mahetlwe',
  'Medie',
  'Metsimotlhabe',
  'Mmankgodi',
  'Mmanoko',
  'Mmatseta',
  'Mmopane',
  'Mogoditshane',
  'Mogonono',
  'Mokolodi',
  'Molepolole',
  'Ramaphatle',
  'Shadishadi',
  'Sojwe',
  'Thamaga',
  'Tloaneng',
  'Botlhapatlou',
  'Diphuduhudu',
  'Ditshegwane',
  'Dutlwe',
  'Kaudwane',
  'Khudumelapye',
  'Kotolaname',
  'Letlhakeng',
  'Maboane ',
  'Malwelwe ',
  'Mantshwabisi ',
  'Maratswane ',
  'Metsibotlhoko',
  'Monwane ',
  'Moshaweng ',
  'Motokwe ',
  'Ngware ',
  'Salajwe ',
  'Serinane ',
  'Sesung ',
  'Sorilatholo',
  'Takatokwane ',
  'Tsetseng ',
  'Tswaane',
  'Artesia',
  'Bokaa',
  'Dikgonnye',
  'Dikwididi ',
  'Kgomodiatshaba',
  'Khurutshe',
  'Leshibitse ',
  'Mabalane ',
  'Malolwane ',
  'Malotwana Siding ',
  'Matebeleng ',
  'Mmathubudukwane ',
  'Mochudi ',
  'Modipane ',
  'Morwa ',
  'Oliphants Drift ',
  'Oodi ',
  'Pilane Station ',
  'Ramonaka ',
  'Ramotlabaki ',
  'Rasesa ',
  'Sikwane',
  'Botalaote ',
  'Butale ',
  'Ditladi ',
  'Gambule ',
  'Gulubane ',
  'Gungwe ',
  'Jackalas ',
  'Jackalas ',
  'Kalakamati ',
  'Kgari ',
  'Letsholathebe ',
  'Mabudzane ',
  'Makaleng ',
  'Mambo ',
  'Mapoka ',
  'Masingwaneng ',
  'Masukwane ',
  'Masunga ',
  'Matenge ',
  'Matopi ',
  'Matshelagabedi ',
  'Matsiloje ',
  'Mbalambi ',
  'Moroka ',
  'Mosojane ',
  'Mowana ',
  'Mulambakwena ',
  'Nlakhwane ',
  'Pataya Matebele ',
  'Pole ',
  'Ramokgwebana ',
  'Sechele ',
  'Sekakangwe ',
  'Senyawe ',
  'Shashe Bridge ',
  'Siviya ',
  'Tati Siding ',
  'Themashanga ',
  'Toteng ',
  'Tsamaya ',
  'Tshesebe ',
  'Vukwi ',
  'Zwenshambe',
  'Borolong ',
  'Borotsi ',
  'Chadibe ',
  'Changate ',
  'Dagwi ',
  'Dukwi ',
  'Goshwe ',
  'Gweta ',
  'Jamataka ',
  'Kutamogree ',
  'Lepashe ',
  'Lobatse',
  'Mabesekwa ',
  'Mafongo / Hobona ',
  'Maitengwe ',
  'Makuta ',
  'Mandunyane ',
  'Maposa ',
  'Marapong ',
  'Marobela ',
  'Mathangwane ',
  'Matobo ',
  'Matsitama ',
  'Mmanxotae ',
  'Mmeya ',
  'Mokubilo ',
  'Mosetse ',
  'Nata ',
  'Natale ',
  'Nkange ',
  'Nshakashokwe ',
  'Orapa',
  'Nswazwi ',
  'Sebina ',
  'Semitwe ',
  'Senete ',
  'Sepako ',
  'Shashe-Mooke ',
  'Shashe/ Semotswane ',
  'Tonota ',
  'Tshokatshaa ',
  'Tutume ',
  'Zoroga',
  'Bodibeng ',
  'Botlhatlogo ',
  'Chanoga ',
  'Habu ',
  'Kareng ',
  'Kgakge / Makakung ',
  'Komana ',
  'Mababe ',
  'Makalamabedi ',
  'Matlapana ',
  'Matsaudi / Sakapne ',
  'Maun ',
  'Phuduhudu ',
  'Sankuyo ',
  'Sehithwa ',
  'Semboyo ',
  'Shorobe ',
  'Toteng ',
  'Tsao',
  'Beetsha ',
  'Chukumuchu ',
  'Eretsha ',
  'Etsha ',
  'Gani ',
  'Gonutsuga ',
  'Gudingwa ',
  'Gumare ',
  'Ikoga ',
  'Kajaja ',
  'Kauxwhi ',
  'Mogomotho ',
  'Mohembo East ',
  'Mohembo West ',
  'Mokgacha ',
  'Ngarange ',
  'Nokaneng ',
  'Nxamasere ',
  'Nxaunxau ',
  'Qangwa ',
  'Samochema ',
  'Sekondomboro ',
  'Sepopa ',
  'Seronga ',
  'Shakawe ',
  'Tobere ',
  'Tubu ',
  'Xakao ',
  'Xaxa ',
  'Xhauga',
  'Kachikau ',
  'Kasane ',
  'Kavimba ',
  'Kazungula ',
  'Lesoma ',
  'Muchinje/Mabele ',
  'Pandamatenga ',
  'Parakarungu ',
  'Satau',
  'Bere ',
  'Charles Hill ',
  'Chobokwane ',
  'Dekar ',
  'East Hanahai ',
  'Ghanzi ',
  'Groote Laagte ',
  'Kacgae ',
  'Karakobis ',
  'Kule ',
  'Makunda ',
  'Ncojane ',
  'New Xade ',
  'New Xanagas ',
  'Qabo ',
  'Tsootsha ',
  'West Hanahai',
  'Bogogobo',
  'Bokspits ',
  'Bray ',
  'Gachibana ',
  'Khisa ',
  'Khuis ',
  'Khwawa ',
  'Kokotsha ',
  'Kolonkwane ',
  'Makopong ',
  'Maleshe ',
  'Maralaleng ',
  'Maubelo',
  'Middlepits ',
  'Omaweneno ',
  'Phepheng/ Draaihoek ',
  'Rapples Pan ',
  'Struizendam ',
  'Tsabong ',
  'Vaalhoek ',
  'Werda',
  'Hukuntsi ',
  'Hunhukwe ',
  'Inalegolo ',
  'Kang ',
  'Lehututu ',
  'Lokgwabe ',
  'Make ',
  'Monong ',
  'Ncaang ',
  'Ngwatle ',
  'Phuduhudu ',
  'Tshane ',
  'Ukwi ',
  'Zutswa'
];
