name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6 # Change to your desired Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase login:ci --no-localhost --token "$FIREBASE_TOKEN"
          firebase deploy --only hosting

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
